# -*- coding: utf-8 -*-
"""Niharika_Nashine_dl2_Bayesian_network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzY8V53zq1fLaBOxAC8VZ5LCYdq41Y2f
"""

!pip install numpy scipy pgmpy

#bayesian model
from pgmpy.models import BayesianModel

"""create an empty bayesian network and add nodes,edges to it"""

model=BayesianModel()

model.add_nodes_from(['smog','traffic'])
model.add_edge('smog','traffic')

model.nodes()

model.edges()

model.add_edge('accident','traffic')
model.nodes()

model.edges()

!pip install --upgrade numpy

"""Define CPD's for all the nodes and add them to the network"""

import numpy as np

# If 'product' is missing in numpy, force it to point to np.prod
if not hasattr(np, 'product'):
    np.product = np.prod

from pgmpy.factors.discrete import TabularCPD


from pgmpy.factors.discrete import TabularCPD
from pgmpy.factors.discrete import TabularCPD
cpd_smog=TabularCPD('smog',2,[[0.4],[0.6]])
cpd_accident=TabularCPD('accident',2,[[0.2],[0.8]])
cpd_traffic=TabularCPD('traffic',2,[[0.9,0.6,0.7,0.1],
                                    [0.1,0.4,0.3,0.9]],
                                    evidence=['smog','accident'],
                                    evidence_card=[2,2])
print("CPD for Smog",cpd_smog,end="\n")
print("CPD for Accident",cpd_accident,end="\n")
print("CPD for Traffic",cpd_traffic,end="\n")



model.add_cpds(cpd_smog,cpd_accident,cpd_traffic)
model.get_cpds()

